// Generated font manifest
export const BUNDLED_FONTS: string[] = [
  "Abril Fatface",
  "Alex Brush",
  "Allura",
  "Amatic SC",
  "Anton",
  "Bebas Neue",
  "Cardo",
  "Caveat",
  "Cinzel Decorative",
  "Cinzel",
  "Cormorant Garamond",
  "Cormorant",
  "Dancing Script",
  "EB Garamond",
  "Great Vibes",
  "Handlee",
  "Inter",
  "JetBrains Mono",
  "Josefin Sans",
  "Jost",
  "Julius Sans One",
  "Kaushan Script",
  "Lato",
  "Lobster",
  "Lora",
  "Marcellus",
  "Merriweather",
  "Montserrat",
  "Nunito",
  "Pacifico",
  "Parisienne",
  "Petit Formal Script",
  "Playfair Display",
  "Poppins",
  "Prata",
  "Quicksand",
  "Raleway",
  "Sacramento",
  "Shadows Into Light",
  "Space Mono",
  "Tangerine",
  "Work Sans"
];
